name: Main
on: 
  push:
    branches-ignore:
    - 'releases/**'
    paths-ignore:
    - 'dist/**'
    - 'data/translations/**'
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - 'dist/**'
    - 'data/translations/**'
    - '**.md'
    - '.github/workflows/release.yml'
    - '.gitignore'
jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        echo $MAKEFLAGS
        git submodule init
        git submodule update

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qt5-default qt5-qmake libqt5x11extras5-dev qttools5-dev-tools qtmultimedia5-dev qtbase5-dev qtbase5-dev-tools

    - name: Build
      run: |
        qmake "DEFINES += PORTABLE_MODE"
        make -j2
  Windows:
    runs-on: windows-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update

    - name: Install Qt
      uses: jurplel/install-qt-action@v1
      with:
        arch: win64_mingw73

    - name: Enable Git symlinks
      run: git config --global core.symlinks true

    - name: Build
      run: |
        qmake "DEFINES += PORTABLE_MODE"
        make -j2
