name: Main
on: 
  push:
    paths-ignore:
    - 'dist/**'
    - '*.md'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - 'dist/**'
    - '*.md'
    - '.gitignore'
jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 5

    - name: Build
      uses: docker://shatur95/crow-translate:ubuntu-18.04
      with:
        args: -c "qmake && make"
  Windows:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
      with:
        arch: win64_mingw73

    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: recursive
        fetch-depth: 5

    - name: Build
      run: |
        qmake
        make
