name: Main

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build
      uses: docker://shatur95/crow-translate:ubuntu-18.04
      with:
        args: -c "qmake && make"
  Windows:
    runs-on: windows-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
      with:
        arch: win64_mingw73

    - name: Clone repo
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build
      run: |
        qmake
        make
